server:
  port: 8080
  error:
    whitelabel:
      enabled: false

gateway: # Custom gateway configuration
  public-routes:
    - /api/users/v1/auth/**
    - /api/pdf/**
    - /api/users/v1/api-docs
    - /api/pdf/v1/api-docs
  service-urls:
    user-service: http://localhost:8091
    pdf-service: http://localhost:8090
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /api/users/v1/api-docs
      - name: PDF Service
        url: /api/pdf/v1/api-docs
    urls-primary-name: User Service
  api-docs:
    enabled: true

# Common configuration
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG
    com:
      tu2l:
        gateway: DEBUG
        pdf: DEBUG
    reactor:
      netty: INFO
  file:
    name: ../etc/logs/gateway-service/app.log
  logback:
    rollingpolicy:
      file-name-pattern: ../etc/logs/gateway-service/%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 7

jwt:
  secret-key: ${JWT_SECRET_KEY:dev-secret-key-must-be-at-least-256-bits-or-32-characters-long}
  access-token:
    expiration-minutes: 15
  refresh-token:
    expiration-days: 7
  issuer: resume-builder-app
