-- Baseline schema for user-service, generated from the JPA entity model (Postgres dialect).
-- Mirrors what Hibernate `ddl-auto=create` produces; ddl-auto is now `validate`, so this
-- migration is the single source of truth for the schema.

create table user_profiles (
    id           bigint generated by default as identity primary key,
    created_at   timestamp(6) not null,
    updated_at   timestamp(6) not null,
    first_name   varchar(50),
    middle_name  varchar(50),
    last_name    varchar(50),
    phone_number varchar(15)
);

create table user_account_status (
    id                    bigint generated by default as identity primary key,
    created_at            timestamp(6) not null,
    updated_at            timestamp(6) not null,
    enabled               boolean not null,
    email_verified        boolean not null,
    phone_verified        boolean not null,
    failed_login_attempts integer,
    account_locked_until  timestamp(6),
    last_login_at         timestamp(6)
);

create table users (
    id                bigint generated by default as identity primary key,
    created_at        timestamp(6) not null,
    updated_at        timestamp(6) not null,
    email             varchar(100) not null,
    username          varchar(50) not null,
    role              varchar(20) not null check (role in ('USER', 'ADMIN', 'MODERATOR', 'GUEST')),
    oauth_user        boolean not null,
    password          varchar(255),
    profile_id        bigint not null unique,
    account_status_id bigint not null unique,
    deleted_at        timestamp(6),
    constraint uk_username unique (username),
    constraint uk_email unique (email),
    constraint fk_users_profile foreign key (profile_id) references user_profiles,
    constraint fk_users_account_status foreign key (account_status_id) references user_account_status
);

create table user_credentials (
    id         bigint generated by default as identity primary key,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    user_id    bigint,
    token      varchar(64) not null,
    expires_at timestamp(6) not null,
    issued_at  timestamp(6) not null,
    token_type varchar(20) not null check (token_type in ('ACCESS', 'REFRESH', 'PASSWORD_RESET', 'EMAIL_VERIFICATION')),
    issuer     varchar(100) not null,
    active     boolean not null,
    constraint fk_user_credentials_user foreign key (user_id) references users
);

create index idx_user_id on user_credentials (user_id);
create index idx_user_active on user_credentials (user_id, active);
create index idx_token_type on user_credentials (token_type, active);

create table audit_events (
    id         bigint generated by default as identity primary key,
    user_id    bigint,
    event_type varchar(40) not null check (event_type in ('USER_REGISTERED', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'ACCOUNT_ENABLED', 'ACCOUNT_DISABLED', 'VERIFICATION_RESENT', 'LOGOUT', 'TOKEN_REFRESHED', 'TOKEN_REUSE_DETECTED', 'PASSWORD_RESET_REQUESTED', 'PASSWORD_RESET_COMPLETED', 'EMAIL_VERIFIED', 'ROLE_ASSIGNED', 'PROFILE_UPDATED')),
    ip_address varchar(64),
    user_agent varchar(512),
    details    varchar(512),
    created_at timestamp(6) not null
);

create index idx_audit_user_id on audit_events (user_id);
create index idx_audit_event_type on audit_events (event_type);
create index idx_audit_created_at on audit_events (created_at);
