### request - Login User
POST http://localhost:8080/api/users/auth/authenticate
Content-Type: application/json
Accept: application/json

{
  "usernameOrEmail": "john_doe999",
  "email": "john.do99e@example.com",
  "password": "SecurePass123!"
}

### request - Refresh Token
POST http://localhost:8080/api/users/auth/refresh-token
Content-Type: application/json
Accept: application/json

{
  "username": "john_doe999",
  "refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJ0b2tlblR5cGUiOiJyZWZyZXNoIiwic3ViIjoiam9obl9kb2U5OTkiLCJpc3MiOiJyZXN1bWUtYnVpbGRlci1hcHAiLCJpYXQiOjE3NjY4NjMyMjksImV4cCI6MTc2NzQ2ODAyOX0.2EYOpMdSA10TsD8G5f4Q-TspGI7LUWXb_yjU0t3hWNkvKsez6FnLwrrnfPsm9919"
}

### request - Get User Profile
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiVVNFUiIsImVtYWlsIjoiam9obi5kbzk5ZUBleGFtcGxlLmNvbSIsInN1YiI6ImpvaG5fZG9lOTk5IiwiaXNzIjoicmVzdW1lLWJ1aWxkZXItYXBwIiwiaWF0IjoxNzY2ODYzNjM5LCJleHAiOjE3NjY4NjQ1Mzl9.UP2bLPncwRUBBCsoTIjvGDcQvfEYgbJXtOFCBS-m8lUhPnzF5vNVQIdz_DhH4ZZj