### request - Login User
POST http://localhost:8080/api/users/auth/authenticate
Content-Type: application/json
Accept: application/json

{
  "usernameOrEmail": "john_doe999",
  "email": "john.do99e@example.com",
  "password": "SecurePass123!"
}

### request - Refresh Token
POST http://localhost:8080/api/users/auth/refresh-token
Content-Type: application/json
Accept: application/json

{
  "username": "john_doe999",
  "refreshToken": "eyJhbGciOiJIUzM4NCJ9.eyJ0b2tlblR5cGUiOiJyZWZyZXNoIiwic3ViIjoiam9obl9kb2U5OTkiLCJpc3MiOiJyZXN1bWUtYnVpbGRlci1hcHAiLCJqdGkiOiJhMmEzYjY2OC1jNTY0LTQzZjItOWRlMC02ZjY3ZDFmYjYzOTgiLCJpYXQiOjE3NjY5Mzk0MDIsImV4cCI6MTc2NzU0NDIwMn0.wLhvZmd0Wv6A5YQIBBwcJ3hCqM85-0utZ8_XXFp21Jsbx2fZ6Bck1Lzdisy0pONa"
}

### request - Get User Profile
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ0b2tlblR5cGUiOiJyZWZyZXNoIiwic3ViIjoiam9obl9kb2U5OTkiLCJpc3MiOiJyZXN1bWUtYnVpbGRlci1hcHAiLCJqdGkiOiJkN2VmYWZkNS1hNDhlLTQ3NWMtYjQ5Yy01NmY4OWNhNDA2MjkiLCJpYXQiOjE3NjY5MzkxODEsImV4cCI6MTc2NzU0Mzk4MX0.uFWtWmzsecObBY46cLnt5wuHAtRzAzd12wWRosYlDvH1-A72V7hQ4_IgyWD1m176